# Generated by Django 5.0.1 on 2026-06-07 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster_url', models.URLField(max_length=1000)),
                ('banner_url', models.URLField(max_length=1000)),
                ('video_url', models.URLField(default='https://www.w3schools.com/html/mov_bbb.mp4', max_length=1000)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('release_year', models.IntegerField(default=2024)),
                ('language', models.CharField(default='English', max_length=100)),
                ('duration', models.CharField(default='2h 15m', max_length=50)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('cast', models.TextField(help_text='Comma-separated cast list')),
                ('crew', models.TextField(default='Director: John Doe', help_text='Comma-separated crew list')),
                ('genres', models.ManyToManyField(related_name='movies', to='cine_verse.genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Basic', max_length=50)),
                ('avatar_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('favorite_genre', models.CharField(default='Sci-Fi', max_length=100)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='cine_verse.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(blank=True, related_name='watchlisted_by', to='cine_verse.movie')),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(default=0, help_text='Percentage of movie watched (0-100)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine_verse.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
