# Generated by Django 5.0.1 on 2026-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_verse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genre',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='cine_verse.genre'),
        ),
    ]
