# Generated by Django 5.0.1 on 2026-06-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_verse', '0003_movie_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order of displaying in lists'),
        ),
    ]
