# Generated by Django 5.0.1 on 2026-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_verse', '0004_movie_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites_order',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchlist_order',
            field=models.TextField(blank=True, default=''),
        ),
    ]
