# Generated by Django 5.0.1 on 2026-06-13 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_verse', '0005_userprofile_favorites_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='cine_verse.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='part_name',
            field=models.CharField(blank=True, help_text="e.g. 'Season 1', 'Season 2', or sequel subtitle like 'Across the Spider-Verse'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='part_number',
            field=models.IntegerField(blank=True, help_text='Season number for TV shows, or chronological part number for movie sequels.', null=True),
        ),
    ]
