# Generated by Django 5.2.4 on 2025-08-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studinfo',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='studinfo',
            old_name='lname',
            new_name='lastname',
        ),
    ]
